name: build-deploy

on:
  push:
    branches: main

jobs:
  use-build:
    uses: olets/cleanandelegant.com/.github/workflows/build.yml@main

  deploy:
    needs: use-build

    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact ⏬
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist

      - name: Upload FTP 🚀
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: dist
          remoteDir: html

